# code generated by claude: "I need spa.txt to be formatted like eng-fra.txt so it can be put through the same attention network"
# i attached the mentioned files to the prompt

with open("data/spa.txt", "r") as f_in, open("data/eng-spa.txt", "w") as f_out:
    for line in f_in:
        parts = line.strip().split("\t")
        f_out.write(f"{parts[0]}\t{parts[1]}\n")